<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductOption;
use App\Models\ProductOptionItem;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Restaurant 1 : Le Bistro Parisien - Catégories 1-5
        $productsR1 = [
            // Entrées (catégorie 1)
            [
                'restaurant_id' => 1, 'category_id' => 1,
                'name' => 'Foie Gras Maison',
                'description' => 'Foie gras de canard mi-cuit, chutney de figues, pain brioché toasté',
                'price' => 16.90,
                'compare_price' => 19.90,
                'cost_price' => 8.50,
                'preparation_time' => 10,
                'calories' => 450,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['entrée', 'gastronomique', 'fait maison']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 1,
                'name' => 'Soupe à l\'Oignon Gratinée',
                'description' => 'Soupe traditionnelle gratinée au gruyère, croûtons maison',
                'price' => 11.90,
                'compare_price' => null,
                'cost_price' => 4.50,
                'preparation_time' => 15,
                'calories' => 320,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['soupe', 'traditionnel', 'chaud']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 1,
                'name' => 'Salade de Chèvre Chaud',
                'description' => 'Salade verte, chèvre rôti, miel, noix, vinaigrette balsamique',
                'price' => 13.90,
                'compare_price' => null,
                'cost_price' => 5.00,
                'preparation_time' => 10,
                'calories' => 280,
                'is_vegetarian' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['salade', 'végétarien', 'frais']),
                'allergens' => json_encode(['lactose', 'fruits à coque']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 1,
                'name' => 'Tartare de Saumon',
                'description' => 'Saumon frais coupé au couteau, avocat, citron vert, aneth',
                'price' => 15.90,
                'compare_price' => null,
                'cost_price' => 7.00,
                'preparation_time' => 12,
                'calories' => 350,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['poisson', 'frais', 'entrée']),
                'allergens' => json_encode(['poisson']),
            ],
            
            // Plats Principaux (catégorie 2)
            [
                'restaurant_id' => 1, 'category_id' => 2,
                'name' => 'Bœuf Bourguignon',
                'description' => 'Bœuf mijoté au vin rouge, lardons, champignons, oignons grelot, purée maison',
                'price' => 22.90,
                'compare_price' => 25.90,
                'cost_price' => 10.00,
                'preparation_time' => 25,
                'calories' => 650,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['viande', 'traditionnel', 'mijoté']),
                'allergens' => json_encode(['lactose', 'sulfites']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 2,
                'name' => 'Magret de Canard',
                'description' => 'Magret de canard rôti, sauce au miel et vinaigre balsamique, gratin dauphinois',
                'price' => 24.90,
                'compare_price' => null,
                'cost_price' => 11.00,
                'preparation_time' => 20,
                'calories' => 580,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['canard', 'gastronomique']),
                'allergens' => json_encode(['lactose']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 2,
                'name' => 'Filet de Bar',
                'description' => 'Filet de bar rôti, risotto crémeux aux petits légumes, sauce citronnée',
                'price' => 26.90,
                'compare_price' => null,
                'cost_price' => 12.00,
                'preparation_time' => 22,
                'calories' => 420,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['poisson', 'gastronomique', 'léger']),
                'allergens' => json_encode(['poisson', 'lactose']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 2,
                'name' => 'Risotto aux Cèpes',
                'description' => 'Risotto crémeux aux cèpes, parmesan, huile de truffe',
                'price' => 18.90,
                'compare_price' => null,
                'cost_price' => 7.50,
                'preparation_time' => 20,
                'calories' => 480,
                'is_vegetarian' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['végétarien', 'italien', 'champignons']),
                'allergens' => json_encode(['lactose', 'gluten']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 2,
                'name' => 'Côte de Veau',
                'description' => 'Côte de veau aux morilles, purée de céleri, légumes de saison',
                'price' => 28.90,
                'compare_price' => null,
                'cost_price' => 13.50,
                'preparation_time' => 25,
                'calories' => 550,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['viande', 'gastronomique']),
                'allergens' => json_encode(['lactose']),
            ],
            
            // Desserts (catégorie 3)
            [
                'restaurant_id' => 1, 'category_id' => 3,
                'name' => 'Crème Brûlée',
                'description' => 'Crème brûlée à la vanille de Madagascar, cassonade caramélisée',
                'price' => 9.90,
                'compare_price' => null,
                'cost_price' => 3.50,
                'preparation_time' => 5,
                'calories' => 380,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['dessert', 'classique', 'vanille']),
                'allergens' => json_encode(['lactose', 'œufs']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 3,
                'name' => 'Tarte Tatin',
                'description' => 'Tarte aux pommes caramélisées, crème fraîche, glace vanille',
                'price' => 10.90,
                'compare_price' => 12.90,
                'cost_price' => 4.00,
                'preparation_time' => 8,
                'calories' => 420,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['dessert', 'pomme', 'classique']),
                'allergens' => json_encode(['gluten', 'lactose', 'œufs']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 3,
                'name' => 'Fondant au Chocolat',
                'description' => 'Fondant au chocolat cœur coulant, glace vanille bourbon',
                'price' => 11.90,
                'compare_price' => null,
                'cost_price' => 4.50,
                'preparation_time' => 10,
                'calories' => 550,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['chocolat', 'dessert', 'gourmand']),
                'allergens' => json_encode(['gluten', 'lactose', 'œufs']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 3,
                'name' => 'Mousse au Chocolat',
                'description' => 'Mousse au chocolat noir 70%, éclats de cacao, chantilly',
                'price' => 8.90,
                'compare_price' => null,
                'cost_price' => 3.00,
                'preparation_time' => 5,
                'calories' => 350,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['chocolat', 'mousse', 'maison']),
                'allergens' => json_encode(['lactose', 'œufs']),
            ],
            [
                'restaurant_id' => 1, 'category_id' => 3,
                'name' => 'Assiette de Fromages',
                'description' => 'Sélection de 5 fromages français, confiture de figues, pain aux noix',
                'price' => 13.90,
                'compare_price' => null,
                'cost_price' => 6.00,
                'preparation_time' => 5,
                'calories' => 480,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['fromage', 'français', 'dégustation']),
                'allergens' => json_encode(['lactose', 'gluten', 'fruits à coque']),
            ],
        ];

        // Restaurant 2 : Pizza Roma - Catégories 6-11
        $productsR2 = [
            // Pizzas Classiques (catégorie 6)
            [
                'restaurant_id' => 2, 'category_id' => 6,
                'name' => 'Margherita',
                'description' => 'Sauce tomate, mozzarella fior di latte, basilic frais',
                'price' => 10.90,
                'compare_price' => null,
                'cost_price' => 3.50,
                'preparation_time' => 12,
                'calories' => 750,
                'is_vegetarian' => true,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['classique', 'végétarien']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 2, 'category_id' => 6,
                'name' => 'Regina',
                'description' => 'Sauce tomate, mozzarella, jambon, champignons frais',
                'price' => 12.90,
                'compare_price' => null,
                'cost_price' => 4.50,
                'preparation_time' => 14,
                'calories' => 820,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['classique', 'jambon']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 2, 'category_id' => 6,
                'name' => 'Diavola',
                'description' => 'Sauce tomate, mozzarella, salami piquant, piments',
                'price' => 13.90,
                'compare_price' => null,
                'cost_price' => 5.00,
                'preparation_time' => 14,
                'calories' => 880,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['piquant', 'viande']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 2, 'category_id' => 6,
                'name' => 'Quattro Stagioni',
                'description' => 'Sauce tomate, mozzarella, jambon, artichauts, champignons, olives',
                'price' => 14.90,
                'compare_price' => null,
                'cost_price' => 5.50,
                'preparation_time' => 15,
                'calories' => 850,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['classique', 'complet']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 2, 'category_id' => 6,
                'name' => 'Capricciosa',
                'description' => 'Sauce tomate, mozzarella, jambon, artichauts, olives, œuf',
                'price' => 13.90,
                'compare_price' => null,
                'cost_price' => 5.00,
                'preparation_time' => 15,
                'calories' => 860,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['classique', 'complet']),
                'allergens' => json_encode(['gluten', 'lactose', 'œufs']),
            ],
            
            // Pâtes Fraîches (catégorie 8)
            [
                'restaurant_id' => 2, 'category_id' => 8,
                'name' => 'Spaghetti Carbonara',
                'description' => 'Spaghetti frais, guanciale, œufs, pecorino, poivre noir',
                'price' => 14.90,
                'compare_price' => null,
                'cost_price' => 5.50,
                'preparation_time' => 15,
                'calories' => 750,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['pâtes', 'classique', 'italien']),
                'allergens' => json_encode(['gluten', 'lactose', 'œufs']),
            ],
            [
                'restaurant_id' => 2, 'category_id' => 8,
                'name' => 'Lasagnes Bolognaises',
                'description' => 'Lasagnes maison, sauce bolognaise mijotée, béchamel, parmesan',
                'price' => 13.90,
                'compare_price' => null,
                'cost_price' => 5.00,
                'preparation_time' => 20,
                'calories' => 820,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['pâtes', 'gratiné', 'viande']),
                'allergens' => json_encode(['gluten', 'lactose', 'œufs']),
            ],
            [
                'restaurant_id' => 2, 'category_id' => 8,
                'name' => 'Penne Arrabiata',
                'description' => 'Pâtes penne, sauce tomate épicée, ail, basilic, pecorino',
                'price' => 11.90,
                'compare_price' => null,
                'cost_price' => 3.50,
                'preparation_time' => 12,
                'calories' => 580,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['pâtes', 'piquant', 'végétarien']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 2, 'category_id' => 8,
                'name' => 'Tagliatelles aux Truffes',
                'description' => 'Tagliatelles fraîches, crème de truffe, champignons, parmesan',
                'price' => 18.90,
                'compare_price' => 22.90,
                'cost_price' => 8.00,
                'preparation_time' => 18,
                'calories' => 680,
                'is_vegetarian' => true,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['pâtes', 'truffe', 'gastronomique']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
        ];

        // Restaurant 3 : Sushi Master - Catégories 12-16
        $productsR3 = [
            // Sushis (catégorie 12)
            [
                'restaurant_id' => 3, 'category_id' => 12,
                'name' => 'Sushi Saumon',
                'description' => '2 pièces de nigiri saumon frais',
                'price' => 5.90,
                'compare_price' => null,
                'cost_price' => 2.50,
                'preparation_time' => 10,
                'calories' => 120,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['sushi', 'saumon', 'japonais']),
                'allergens' => json_encode(['poisson']),
            ],
            [
                'restaurant_id' => 3, 'category_id' => 12,
                'name' => 'Sushi Thon',
                'description' => '2 pièces de nigiri thon rouge',
                'price' => 6.90,
                'compare_price' => null,
                'cost_price' => 3.00,
                'preparation_time' => 10,
                'calories' => 110,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['sushi', 'thon', 'japonais']),
                'allergens' => json_encode(['poisson']),
            ],
            [
                'restaurant_id' => 3, 'category_id' => 12,
                'name' => 'Sushi Crevette',
                'description' => '2 pièces de nigiri crevette cuite',
                'price' => 5.90,
                'compare_price' => null,
                'cost_price' => 2.50,
                'preparation_time' => 10,
                'calories' => 100,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['sushi', 'crevette', 'japonais']),
                'allergens' => json_encode(['crustacés']),
            ],
            
            // Makis (catégorie 13)
            [
                'restaurant_id' => 3, 'category_id' => 13,
                'name' => 'California Saumon Avocat',
                'description' => '8 pièces - Saumon, avocat, concombre, riz vinaigré',
                'price' => 10.90,
                'compare_price' => null,
                'cost_price' => 4.50,
                'preparation_time' => 15,
                'calories' => 320,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['maki', 'saumon', 'avocat']),
                'allergens' => json_encode(['poisson']),
            ],
            [
                'restaurant_id' => 3, 'category_id' => 13,
                'name' => 'Maki Thon Épicé',
                'description' => '8 pièces - Thon épicé, ciboulette, sauce piquante',
                'price' => 11.90,
                'compare_price' => null,
                'cost_price' => 5.00,
                'preparation_time' => 15,
                'calories' => 340,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['maki', 'thon', 'épicé']),
                'allergens' => json_encode(['poisson']),
            ],
            
            // Plats Chauds (catégorie 14)
            [
                'restaurant_id' => 3, 'category_id' => 14,
                'name' => 'Ramen au Porc',
                'description' => 'Bouillon miso, porc chashu, œuf mollet, nori, légumes',
                'price' => 14.90,
                'compare_price' => null,
                'cost_price' => 6.00,
                'preparation_time' => 20,
                'calories' => 650,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['ramen', 'soupe', 'chaud']),
                'allergens' => json_encode(['gluten', 'œufs', 'soja']),
            ],
            [
                'restaurant_id' => 3, 'category_id' => 14,
                'name' => 'Udon Sauté aux Légumes',
                'description' => 'Nouilles udon sautées, légumes croquants, sauce soja',
                'price' => 12.90,
                'compare_price' => null,
                'cost_price' => 4.50,
                'preparation_time' => 15,
                'calories' => 480,
                'is_vegetarian' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['udon', 'végétarien', 'wok']),
                'allergens' => json_encode(['gluten', 'soja']),
            ],
        ];

        // Restaurant 4 : Burger House - Catégories 17-22
        $productsR4 = [
            // Burgers Classiques (catégorie 17)
            [
                'restaurant_id' => 4, 'category_id' => 17,
                'name' => 'Classic Burger',
                'description' => 'Steak haché 150g, salade, tomate, oignon, cornichons, sauce maison',
                'price' => 9.90,
                'compare_price' => null,
                'cost_price' => 3.50,
                'preparation_time' => 10,
                'calories' => 650,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['burger', 'classique', 'bœuf']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 4, 'category_id' => 17,
                'name' => 'Cheeseburger',
                'description' => 'Steak haché 150g, cheddar fondant, salade, tomate, oignon',
                'price' => 10.90,
                'compare_price' => null,
                'cost_price' => 4.00,
                'preparation_time' => 10,
                'calories' => 720,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['burger', 'fromage', 'bœuf']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 4, 'category_id' => 17,
                'name' => 'Bacon Burger',
                'description' => 'Steak 150g, bacon croustillant, cheddar, oignons caramélisés',
                'price' => 12.90,
                'compare_price' => null,
                'cost_price' => 5.00,
                'preparation_time' => 12,
                'calories' => 780,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['burger', 'bacon', 'bœuf']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            [
                'restaurant_id' => 4, 'category_id' => 17,
                'name' => 'Double Cheese',
                'description' => 'Double steak 150g, double cheddar, bacon, sauce BBQ',
                'price' => 15.90,
                'compare_price' => null,
                'cost_price' => 6.50,
                'preparation_time' => 15,
                'calories' => 980,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['burger', 'double', 'fromage']),
                'allergens' => json_encode(['gluten', 'lactose']),
            ],
            
            // Accompagnements (catégorie 19)
            [
                'restaurant_id' => 4, 'category_id' => 19,
                'name' => 'Frites Maison',
                'description' => 'Frites fraîches coupées main, sel de mer',
                'price' => 3.90,
                'compare_price' => null,
                'cost_price' => 1.00,
                'preparation_time' => 8,
                'calories' => 350,
                'is_vegan' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['frites', 'accompagnement']),
                'allergens' => json_encode([]),
            ],
            [
                'restaurant_id' => 4, 'category_id' => 19,
                'name' => 'Sweet Potato Fries',
                'description' => 'Frites de patate douce, épices douces, sauce au yaourt',
                'price' => 4.90,
                'compare_price' => null,
                'cost_price' => 1.50,
                'preparation_time' => 10,
                'calories' => 320,
                'is_vegetarian' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['patate douce', 'frites']),
                'allergens' => json_encode(['lactose']),
            ],
            [
                'restaurant_id' => 4, 'category_id' => 19,
                'name' => 'Onion Rings',
                'description' => 'Rondelles d\'oignon enrobées de panure croustillante',
                'price' => 5.90,
                'compare_price' => null,
                'cost_price' => 2.00,
                'preparation_time' => 10,
                'calories' => 380,
                'is_vegetarian' => true,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['oignon', 'frit', 'accompagnement']),
                'allergens' => json_encode(['gluten']),
            ],
        ];

        // Restaurant 5 : Le Jardin Vert - Catégories 23-27
        $productsR5 = [
            // Bowls (catégorie 23)
            [
                'restaurant_id' => 5, 'category_id' => 23,
                'name' => 'Buddha Bowl',
                'description' => 'Quinoa, patate douce rôtie, pois chiches, avocat, kale, sauce tahini',
                'price' => 13.90,
                'compare_price' => null,
                'cost_price' => 4.50,
                'preparation_time' => 15,
                'calories' => 450,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['vegan', 'bowl', 'sain']),
                'allergens' => json_encode(['sésame']),
            ],
            [
                'restaurant_id' => 5, 'category_id' => 23,
                'name' => 'Poké Bowl Végétal',
                'description' => 'Riz sushi, tofu mariné, edamame, mangue, avocat, algues',
                'price' => 14.90,
                'compare_price' => null,
                'cost_price' => 5.00,
                'preparation_time' => 12,
                'calories' => 420,
                'is_vegan' => true,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['vegan', 'poké', 'exotique']),
                'allergens' => json_encode(['soja']),
            ],
            [
                'restaurant_id' => 5, 'category_id' => 23,
                'name' => 'Falafel Bowl',
                'description' => 'Falafels maison, houmous, légumes grillés, pita, sauce yaourt végétal',
                'price' => 12.90,
                'compare_price' => null,
                'cost_price' => 4.00,
                'preparation_time' => 15,
                'calories' => 520,
                'is_vegan' => true,
                'is_available' => true,
                'is_featured' => false,
                'tags' => json_encode(['vegan', 'falafel', 'méditerranéen']),
                'allergens' => json_encode(['gluten', 'sésame']),
            ],
            
            // Jus & Smoothies (catégorie 26)
            [
                'restaurant_id' => 5, 'category_id' => 26,
                'name' => 'Green Detox',
                'description' => 'Épinards, concombre, céleri, pomme verte, gingembre, citron',
                'price' => 6.90,
                'compare_price' => null,
                'cost_price' => 2.00,
                'preparation_time' => 5,
                'calories' => 120,
                'is_vegan' => true,
                'is_gluten_free' => true,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['jus', 'detox', 'vert']),
                'allergens' => json_encode([]),
            ],
            [
                'restaurant_id' => 5, 'category_id' => 26,
                'name' => 'Smoothie Bowl Açaï',
                'description' => 'Açaï, banane, granola maison, fruits frais, graines de chia',
                'price' => 10.90,
                'compare_price' => null,
                'cost_price' => 3.50,
                'preparation_time' => 8,
                'calories' => 380,
                'is_vegan' => true,
                'is_available' => true,
                'is_featured' => true,
                'tags' => json_encode(['smoothie', 'açaï', 'fruits']),
                'allergens' => json_encode(['fruits à coque', 'gluten']),
            ],
        ];

        $allProducts = array_merge(
            $productsR1, $productsR2, $productsR3, 
            $productsR4, $productsR5
        );

        foreach ($allProducts as $productData) {
            Product::create($productData);
        }
    }
}