[PHP]
display_errors = Off
log_errors = On
error_log = /var/log/php-fpm.error.log
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
max_execution_time = 300
max_input_time = 300
max_input_vars = 10000
memory_limit = 256M
post_max_size = 100M
upload_max_filesize = 100M
date.timezone = UTC

; Extensions
extension = pdo_mysql
extension = mbstring
extension = zip
extension = gd
extension = bcmath
extension = intl
extension = exif
extension = pcntl